language: go

go:
- 1.6.3

sudo: false

before_install:
  # Redo the travis setup but with the radoondas/jmxproxybeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/radoondas/jmxproxybeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/radoondas/jmxproxybeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/radoondas/jmxproxybeat
  - cd $HOME/gopath/src/github.com/radoondas/jmxproxybeat

install:
  - make
